List<Map<String, dynamic>>  products = [
  {
    'id' : 1,
    'name' : 'Nike Air Max 90',
    'desc' : 'Womens Shoes - Popular',
    'price' : '\$150',
    'img' : 'assets/images/p1.jpg',
    'category' : 'favorite',
    'cimgs' : ['assets/images/p0.jpg', 'assets/images/p11.jpg', 'assets/images/p12.jpg', 'assets/images/p1.jpg'],
  },
  {
    'id' : 2,
    'name' : 'Nike AF1 Shadow',
    'desc' : 'Womens Shoes - Just In',
    'price' : '\$130',
    'img' : 'assets/images/p2.jpg',
    'category' : 'cart',
    'cimgs' : ['assets/images/p21.jpg', 'assets/images/p22.jpg', 'assets/images/p0.jpg', 'assets/images/p2.jpg'],
  },
  {
    'id' : 3,
    'name' : 'Nike Court Legacy',
    'desc' : 'Womens Shoes',
    'price' : '\$150',
    'img' : 'assets/images/p3.jpg',
    'category' : 'favorite',
    'cimgs' : ['assets/images/p31.jpg', 'assets/images/p32.jpg', 'assets/images/p0.jpg', 'assets/images/p3.jpg'],
  },
  {
    'id' : 4,
    'name' : 'Nike Court Legacy Next',
    'desc' : 'Womens Shoes',
    'price' : '\$100',
    'img' : 'assets/images/p4.jpg',
    'category' : 'favorite',
    'cimgs' : ['assets/images/p41.jpg', 'assets/images/p42.jpg', 'assets/images/p0.jpg', 'assets/images/p4.jpg'],
  },
  {
    'id' : 5,
    'name' : "Air Force 1 '07",
    'desc' : '',
    'price' : '\$150',
    'img' : 'assets/images/p5.jpg',
    'category' : 'cart',
    'cimgs' : ['assets/images/p51.jpg', 'assets/images/p52.jpg', 'assets/images/p0.jpg', 'assets/images/p5.jpg'],
  },
  {
    'id' : 6,
    'name' : "Nike Blazer Low '77",
    'desc' : '',
    'price' : '\$120',
    'img' : 'assets/images/p6.jpg',
    'category' : 'cart',
    'cimgs' : ['assets/images/p61.jpg', 'assets/images/p62.jpg', 'assets/images/p0.jpg', 'assets/images/p6.jpg'],
  },
];